#!/bin/bash
# ------------------------------------------------------------------------------
# Bash scripting cheatsheet => https://devhints.io/bash
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Stooges: Honorning Lary, Moe, and Curley ... Nyuk, nyuk, nyuk.
# ------------------------------------------------------------------------------
echo "Operating system: " ${OSTYPE}

# ------------------------------------------------------------------------------
# Define functions and paths for this shell. 
# ------------------------------------------------------------------------------
dotfiles=${HOME}/git/dotfiles
source ${dotfiles}/my_functions
source ${dotfiles}/my_exports
source ${dotfiles}/my_aliases
source ${dotfiles}/my_paths
source ${dotfiles}/my_completions
source ${dotfiles}/my_prompt
