#!/bin/bash
# ------------------------------------------------------------------------------
# I define my path here. My goal it to take complete control of my path.
# ------------------------------------------------------------------------------
if [[ ${OSTYPE} =~ "linux" ]] \
|| [[ ${OSTYPE} =~ "msys" ]]; then
  PATH=${HOME}
fi

# ------------------------------------------------------------------------------
# Linux style machines.
# ------------------------------------------------------------------------------
if [[ ${OSTYPE} =~ "darwin" ]]  \
|| [[ ${OSTYPE} =~ "linux" ]] \
|| [[ ${OSTYPE} =~ "msys" ]]; then
    appendToPath /usr/local/sbin
    appendToPath /usr/local/bin
    appendToPath /usr/sbin
    appendToPath /usr/bin
    appendToPath /sbin
    appendToPath /bin
    appendToPath ${GEM_PATH}/bin
    appendToPath ${HOME}/.vim/bundle/vim-superman/bin
    appendToPath ${HOME}/bin
fi
# ------------------------------------------------------------------------------
# Append directories to path.
# ------------------------------------------------------------------------------
if [[ ${OSTYPE} =~ "msys" ]]; then
  appendToPath /mingw64/bin
  appendToPath /c/Program\ Files/MiKTeX\ 2.9/miktex/bin/x64
  appendToPath /c/ProgramData/chocolatey/bin
  appendToPath /c/tools/ruby25/bin
  appendToPath /c/ProgramData/chocolatey/lib/fzf/tools
  appendToPath /c/Strawberry/c/bin
  appendToPath /c/Strawberry/perl/site/bin
  appendToPath /c/Strawberry/perl/bin
fi

# ------------------------------------------------------------------------------
# Adjust path for Legolas computer.
# ------------------------------------------------------------------------------
if [[ ${OSTYPE} =~ "darwin" ]]; then
  if [[ ${HOSTNAME} =~ "Legolas" ]]; then
    if [[ -d ${HOME}/bin ]]; then
      appendToPath ${HOME}/.cabal/bin
      appendToPath ${HOME}/Library/Haskell/bin
      appendToPath ${HOME}/.local/bin
    fi
  fi
fi

