#!/bin/bash
# ------------------------------------------------------------------------------
# I define my path here. My goal is to append the path in alphabetical order.
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Windows 10 Subsystem for Linux ...
# ------------------------------------------------------------------------------
if [[ ${OSTYPE} =~ "linux" ]]; then
  if [[ ${HOSTNAME} =~ "Gandolf" ]]; then
    PATH=""
    appendToPath /usr/local/sbin
    appendToPath /usr/local/bin
    appendToPath /usr/local/bin
    appendToPath /usr/sbin
    appendToPath /usr/bin
    appendToPath /sbin
    appendToPath /bin
  fi
fi

# ------------------------------------------------------------------------------
# Adjust path for Legolas computer. 
# ------------------------------------------------------------------------------
if [[ ${OSTYPE} =~ "darwin" ]]; then
  if [[ ${HOSTNAME} =~ "Legolas" ]]; then
    if [[ -d ${HOME}/bin ]]; then
      appendToPath ${HOME}/bin
    fi
  fi
fi

# ------------------------------------------------------------------------------
# Append directories to path.
# ------------------------------------------------------------------------------
appendToPath ${GEM_PATH}
appendToPath ${HOME}/.cabal/bin
appendToPath ${HOME}/.local/bin
appendToPath ${HOME}/Library/Haskell/bin
appendToPath $HOME/.vim/bundle/vim-superman/bin
appendToPath /c/Program\ Files/MiKTeX\ 2.9/miktex/bin/x64
appendToPath /c/ProgramData/chocolatey/bin
appendToPath /c/tools/ruby25/bin
