set nocompatible
filetype off
set rtp+=~/git/dotfiles/vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

Plugin 'bling/vim-airline'
Plugin 'bruno-/vim-man'
Plugin 'chriskempson/base16-vim'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'christoomey/vim-tmux-runner'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'edkolev/tmuxline.vim'
Plugin 'eagletmt/ghcmod-vim'
Plugin 'eagletmt/neco-ghc'
Plugin 'ivalkeen/nerdtree-execute'
Plugin 'moll/vim-bbye'
Plugin 'mpickering/hlint-refactor-vim'
Plugin 'neovimhaskell/haskell-vim'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'Shougo/neocomplete.vim'
Plugin 'Shougo/vimproc.vim'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-dispatch'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-pathogen'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-unimpaired'
Plugin 'Twinside/vim-hoogle'
Plugin 'vim-scripts/bufexplorer.zip'
Plugin 'vim-scripts/CycleColor'
Plugin 'traap/vim-dragvisuals'
call vundle#end()
filetype plugin indent on
